//\/\/\/\/\/\/\/\/\/\ ACTION TYPES /\/\/\/\/\/\/\/\/\/\\

export const SET_KEYDOWN = "SET_KEYDOWN";

//\/\/\/\/\/\/\/\/\/\ FETCHES /\/\/\/\/\/\/\/\/\/\\
export const FETCH_URL_POKEMON_START = "FETCH_URL_POKEMON_START";
export const FETCH_URL_POKEMON_SUCCESS = "FETCH_URL_POKEMON_SUCCESS";
export const FETCH_URL_POKEMON_FAILURE = "FETCH_URL_POKEMON_FAILURE";
export const FETCH_URL_POKEMON_COMPLETE = "FETCH_URL_POKEMON_COMPLETE";

export const FETCH_PKMN_START = "FETCH_PKMN_START";
export const FETCH_PKMN_SUCCESS = "FETCH_PKMN_SUCCESS";
export const FETCH_PKMN_FAILURE = "FETCH_PKMN_FAILURE";
export const FETCH_PKMN_COMPLETE = "FETCH_PKMN_COMPLETE";
